#! /usr/bin/env python3

import os
import subprocess
import sys
import textwrap

__version__ = "1.7.0-dev0"

progs = {
    "cat": "Read a fasta file or stream, write to stdout.",
    "fragger": "Read a fasta file or stream, write each fragmented seq to stdout.",
    "longest": "Read a fasta file or stream, write the longest sequence to stdout.",
    "random": "Generate a stream of random sequences in fasta format.",
    "select": "Read a fasta file or stream, write selected sequences to stdout.",
    "sizes": "Read a fasta file or stream, write the sequence sizes to stdout.",
    "summarize": "Read a fasta file or stream, write a summary to stdout.",
    "tidy": "Read a fasta file or stream, write a tidy version to stdout.",
    "wc": "Read a fasta file or stream of nucleotide sequence, write kmer abundance.",
    "wcontext": "Read a fasta file or stream, write sequence flanking a specified word.",
}


def print_help():
    print(f"fah {__version__}\nfasta helpers.\nusage:")
    for p in sorted(progs):
        spacer = " " * (18 - 6 - len(p))
        print(
            "\n".join(
                textwrap.wrap(
                    progs[p],
                    initial_indent=f"fah {p}. {spacer}",
                    subsequent_indent=" " * 18,
                )
            )
        )


def print_help_as_markdown_list():
    for p in sorted(progs):
        print(f"* `fah {p} [ARGS]`. {progs[p]}")


def print_version():
    print(f"fah {__version__}")


a = os.path.split(sys.argv[0])
# print(a[0], a[1])

if len(sys.argv) > 1:
    b = sys.argv[1:]
    if b[0] == "-h" or b[0] == "--help":
        print_help()
        exit(0)
    if b[0] == "-m" or b[0] == "--markdown":
        print_help_as_markdown_list()
        exit(0)
    if b[0] == "-V" or b[0] == "--version":
        print_version()
        exit(0)
    if b[0] not in progs:
        print(f"[ERROR] 'fah {b[0]}' is not valid, try 'fah --help'.", file=sys.stderr)
        exit(1)
    cmd = f"fah-{b[0]}"
    b[0] = os.path.join(a[0], cmd)
    try:
        subprocess.run(b)
    except:
        print(f"[ERROR] {b[0]} not found.", file=sys.stderr)
        exit(1)
    """
        except FileNotFoundError:
            pass
    """

else:
    print_help()
