#! /usr/bin/env python

import sys
import argparse
from Bio import SeqIO

parser = argparse.ArgumentParser()
parser.add_argument(
    "infile", nargs="?", default=sys.stdin, help="filename (default: stdin)"
)
args = parser.parse_args()

for r in SeqIO.parse(args.infile, "fasta"):
    print(f"{r.id}\t{len(str(r.seq))}")
